packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    '@antfu/ni': ^24.1.0
    '@isentinel/eslint-config': 1.0.1
    '@typescript-eslint/utils': 8.30.1
    '@typescript-eslint/parser': 8.30.1
    bumpp: ^10.1.0
    eslint-plugin-pnpm: 0.3.1
    eslint: ^9.22.0
    jiti: 2.4.2
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    '@typescript-eslint/rule-tester': 8.30.1
    eslint-vitest-rule-tester: 2.2.0
    vitest: 3.1.1
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
  utils:
    tinyexec: ^0.3.2
    eslint-doc-generator: 2.1.2

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
