packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalogs:
  cli:
    "@antfu/ni": ^25.0.0
    "@isentinel/eslint-config": 3.0.0-beta.1
    "@typescript-eslint/parser": 8.39.1
    "@typescript-eslint/utils": 8.39.1
    bumpp: ^10.2.3
    eslint: ^9.33.0
    eslint-plugin-pnpm: 1.1.0
    jiti: 2.5.1
    lint-staged: ^16.1.5
    simple-git-hooks: ^2.13.1
    tsdown: ^0.14.1
    tsx: ^4.20.4
    typescript: 5.8.3
    vite: ^7.1.2
  inlined:
    "@antfu/utils": ^9.2.0
  testing:
    "@typescript-eslint/rule-tester": 8.39.1
    eslint-plugin-eslint-plugin: ^7.0.0
    eslint-vitest-rule-tester: 2.2.1
    vitest: 3.2.4
    yaml: ^2.8.1
    "@vitest/eslint-plugin": 1.3.4
  types:
    "@types/node": ^24.2.1
  utils:
    eslint-doc-generator: 2.2.2
    publint: ^0.3.12
    tinyexec: ^1.0.1
    unplugin-unused: ^0.5.1

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
  - unrs-resolver
