packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalogs:
  cli:
    '@isentinel/eslint-config': 1.0.1
    '@antfu/ni': ^24.1.0
    bumpp: ^10.1.0
    eslint: ^9.22.0
    lint-staged: ^15.5.0
    simple-git-hooks: ^2.11.1
    tsx: ^4.19.3
    typescript: ^5.8.2
    unbuild: ^3.5.0
    vite: ^6.2.1
    eslint-plugin-pnpm: 0.3.1
    jiti: 2.4.2
  inlined:
    '@antfu/utils': ^9.1.0
  testing:
    jest: 29.5.0
    eslint-plugin-jest: 28.11.0
    yaml: ^2.7.0
  types:
    '@types/node': ^22.13.10
    '@types/jest': 29.5.0
  utils:
    tinyexec: ^0.3.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
